"""
Curated stakeholder archetypes.

These are the fallback personas used whenever AccountContext.real_data has
no entry (or an empty list) for a given role. They're deliberately written
from enterprise B2B Gen AI deal patterns — adjust priorities/objections to
your vertical as you collect more real debate transcripts.
"""
from __future__ import annotations

from digital_twins.models import StakeholderProfile, StakeholderRole, DataSource

ARCHETYPES: dict[StakeholderRole, StakeholderProfile] = {
    StakeholderRole.CFO: StakeholderProfile(
        role=StakeholderRole.CFO,
        name="Generic CFO",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Total cost of ownership over 3 years, not just license cost",
            "Predictable, defensible ROI tied to a hard metric (headcount, cycle time, revenue)",
            "Avoiding vendor lock-in and renewal-time price shocks",
        ],
        known_objections=[
            "The ROI case relies on soft/unmeasurable benefits",
            "Implementation cost is underestimated",
            "We already have budget committed elsewhere this fiscal year",
        ],
        decision_power=0.9,
        tone="numbers-first, skeptical of vendor enthusiasm, will not be impressed by demos alone",
    ),
    StakeholderRole.CTO: StakeholderProfile(
        role=StakeholderRole.CTO,
        name="Generic CTO",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Architectural fit with existing stack, avoiding a new island of integration debt",
            "Security, data residency, and model governance",
            "Team's ability to maintain/extend this without permanent vendor dependency",
        ],
        known_objections=[
            "How does this integrate with our existing identity/data layer?",
            "What happens to our data — is it used for model training?",
            "We tried something similar 2 years ago and it didn't scale",
        ],
        decision_power=0.85,
        tone="technically rigorous, asks pointed implementation questions, dislikes hand-waving",
    ),
    StakeholderRole.PROCUREMENT: StakeholderProfile(
        role=StakeholderRole.PROCUREMENT,
        name="Generic Procurement Lead",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Contract terms: exit clauses, SLAs, liability caps",
            "Competitive benchmarking against at least 2 other vendors",
            "Compliance with internal vendor risk policy",
        ],
        known_objections=[
            "We need a competitive bid before this can move forward",
            "These payment terms don't match our standard 60-day cycle",
            "Has legal reviewed the data processing addendum?",
        ],
        decision_power=0.6,
        tone="process-driven, will slow things down for the sake of process even if convinced of value",
    ),
    StakeholderRole.END_USER: StakeholderProfile(
        role=StakeholderRole.END_USER,
        name="Generic End User Representative",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Will this actually reduce my daily workload or add another tool to juggle",
            "Ease of adoption, minimal retraining",
            "Trust that outputs are reliable enough to act on without double-checking everything",
        ],
        known_objections=[
            "We already have too many tools — this needs to replace something, not add to the pile",
            "What happens when the AI gets it wrong?",
        ],
        decision_power=0.3,
        tone="pragmatic, cares about day-to-day friction more than strategic narrative",
    ),
    StakeholderRole.CHAMPION: StakeholderProfile(
        role=StakeholderRole.CHAMPION,
        name="Generic Internal Champion",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Looking good internally for having found and pushed this solution",
            "Needs ammunition to defend the deal in internal meetings the vendor isn't in the room for",
            "Wants a fast, visible early win to build momentum",
        ],
        known_objections=[
            "I believe in this, but I need a stronger answer on [X] before I take this to my CFO",
        ],
        decision_power=0.4,
        tone="supportive but pragmatic — will surface the OTHER stakeholders' objections proactively",
    ),
    StakeholderRole.LEGAL_COMPLIANCE: StakeholderProfile(
        role=StakeholderRole.LEGAL_COMPLIANCE,
        name="Generic Legal & Compliance Lead",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Data privacy regulation fit (GDPR/LGPD/sector-specific)",
            "IP ownership of outputs generated by the system",
            "Liability allocation if the AI produces a harmful or incorrect output",
        ],
        known_objections=[
            "Who is liable if this system gives a customer wrong information?",
            "We need an explicit data processing agreement before any pilot with real data",
        ],
        decision_power=0.7,
        tone="formal, risk-averse, will not be rushed",
    ),
    StakeholderRole.SECURITY: StakeholderProfile(
        role=StakeholderRole.SECURITY,
        name="Generic CISO / Security Lead",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Threat model for the agentic system: prompt injection, data exfiltration, tool-call abuse",
            "Audit logging and explainability of agent actions",
            "Compliance with internal AI usage policy",
        ],
        known_objections=[
            "What's the blast radius if one of these agents is compromised or jailbroken?",
            "Can we get a pen test report or SOC 2 before this touches production data?",
        ],
        decision_power=0.75,
        tone="adversarial by design — actively tries to find the failure mode",
    ),
    StakeholderRole.CEO: StakeholderProfile(
        role=StakeholderRole.CEO,
        name="Generic CEO",
        company="",
        source=DataSource.ARCHETYPE,
        priorities=[
            "Strategic narrative: does this make a story we can tell the board/market",
            "Competitive positioning — are we behind or ahead of peers on this",
            "Minimal personal time investment; delegates details but wants the headline",
        ],
        known_objections=[
            "Why this, why now, and why this vendor over the obvious alternatives",
        ],
        decision_power=1.0,
        tone="big-picture, impatient with detail, decisive once convinced of the narrative",
    ),
}


def get_archetype(role: StakeholderRole) -> StakeholderProfile:
    """Return a fresh copy of the archetype for a role (never the shared singleton)."""
    return ARCHETYPES[role].model_copy(deep=True)
